/**
 * Client configuration — AUTO-GENERATED by scripts/apply-config.ts on 2026-04-22T10:22:20.233Z.
 * Source of truth: seed-data.json committed by the onboarding tool.
 * DO NOT hand-edit — run `pnpm apply:config` to regenerate.
 */

export type DashboardType = 'custom' | 'middleware' | 'saas'

export type SidebarTheme = 'light' | 'navy' | 'zoho' | 'slate' | 'neutral'

export interface SyncTargets {
  products:  boolean
  orders:    boolean
  customers: boolean
}

export interface IntegrationsConfig {
  shopify: {
    enabled:  boolean
    storeUrl: string
    sync:     SyncTargets
  }
  bigcommerce: {
    enabled:   boolean
    storeHash: string
    sync:      SyncTargets
  }
}

export interface ClientConfig {
  name:              string
  slug:              string
  adminEmail:        string
  adminFirstName:    string
  adminLastName:     string
  brandPrimaryColor: string
  brandLogoUrl:      string | null
  notes:             string | null
  provisionedAt:     string | null
  provisionedBy:     string | null
  dashboardType:     DashboardType
  sidebarTheme:      SidebarTheme
  integrations:      IntegrationsConfig
}

export const CLIENT_CONFIG: ClientConfig = {
  name:              "WDS Dashboard",
  slug:              "wds",
  adminEmail:        "admin@wds.local",
  adminFirstName:    "Super",
  adminLastName:     "Admin",
  brandPrimaryColor: "#2563EB",
  brandLogoUrl:      null,
  notes:             null,
  provisionedAt:     null,
  provisionedBy:     null,
  dashboardType:     "middleware",
  sidebarTheme:      "light",
  integrations: {
    shopify: {
      enabled:  true,
      storeUrl: "example.myshopify.com",
      sync: {
        products:  true,
        orders:    true,
        customers: true,
      }, 
    },
    bigcommerce: {
      enabled:   false,
      storeHash: "",
      sync: {
        products:  false,
        orders:    false,
        customers: false,
      },
    },
  },
}

export const ENABLED_MODULES: ReadonlySet<string> = new Set([
  "users",
  "roles",
  "email-templates",
  "activity-logs",
  "api-logs",
  "settings",
  "dashboard",
  "connections",
  "sync-history",
  "cron-sync",
  "connections",
])

export function isModuleEnabled(key: string): boolean {
  return ENABLED_MODULES.has(key)
}

export function isIntegrationEnabled(platform: 'shopify' | 'bigcommerce'): boolean {
  return (
    CLIENT_CONFIG.dashboardType === 'middleware' &&
    CLIENT_CONFIG.integrations[platform].enabled
  )
}
