/**
 * Client configuration — AUTO-GENERATED by scripts/apply-config.ts on 2026-05-04T13:58:10.169Z.
 * Source of truth: seed-data.json committed by the onboarding tool.
 * DO NOT hand-edit — run `pnpm apply:config` to regenerate.
 *
 * Runtime helpers (`getClientConfig`, `getEnabledModules`, …) live in
 * `./client-config-runtime.ts` and are re-exported below — that file is
 * hand-written and is NOT touched by `apply-config`.
 */

export type DashboardType = 'custom' | 'middleware' | 'saas'

export type SidebarTheme = 'light' | 'navy' | 'zoho' | 'slate' | 'neutral'

export interface SyncTargets {
  products:  boolean
  orders:    boolean
  customers: boolean
}

export interface IntegrationsConfig {
  shopify: {
    enabled:  boolean
    storeUrl: string
    sync:     SyncTargets
  }
  bigcommerce: {
    enabled:   boolean
    storeHash: string
    sync:      SyncTargets
  }
}

/** Static seed snapshot written by `pnpm apply:config` from seed-data.json. */
export interface StaticClientConfig {
  name:              string
  slug:              string
  adminEmail:        string
  adminFirstName:    string
  adminLastName:     string
  brandPrimaryColor: string
  brandLogoUrl:      string | null
  /** Google Font family name (e.g. "Montserrat"). Null = use the default Inter/Poppins stack. */
  fontFamily:        string | null
  notes:             string | null
  provisionedAt:     string | null
  provisionedBy:     string | null
  dashboardType:     DashboardType
  sidebarTheme:      SidebarTheme
  integrations:      IntegrationsConfig
}

export const STATIC_CLIENT_CONFIG: StaticClientConfig = {
  name:              "wds app demo",
  slug:              "wds-app-demo",
  adminEmail:        "development.qatesting@gmail.com",
  adminFirstName:    "John",
  adminLastName:     "Doe",
  brandPrimaryColor: "#000000",
  brandLogoUrl:      null,
  fontFamily:        "Poppins",
  notes:             null,
  provisionedAt:     "2026-04-22T17:28:36.095Z",
  provisionedBy:     "arvind-webdesk",
  dashboardType:     "middleware",
  sidebarTheme:      "light",
  integrations: {
    shopify: {
      enabled:  true,
      storeUrl: "",
      sync: {
        products:  true,
        orders:    true,
        customers: false,
      },
    },
    bigcommerce: {
      enabled:   false,
      storeHash: "",
      sync: {
        products:  true,
        orders:    true,
        customers: false,
      },
    },
  },
}

export const ENABLED_MODULES: ReadonlySet<string> = new Set([
  "users",
  "roles",
  "email-templates",
  "activity-logs",
  "api-logs",
  "settings",
  "sync-history",
  "cron-sync",
  "dashboard",
  "connections",
])

export function isModuleEnabled(key: string): boolean {
  return ENABLED_MODULES.has(key)
}

export function isIntegrationEnabled(platform: 'shopify' | 'bigcommerce'): boolean {
  return (
    (STATIC_CLIENT_CONFIG.dashboardType === 'middleware' ||
      STATIC_CLIENT_CONFIG.dashboardType === 'custom') &&
    STATIC_CLIENT_CONFIG.integrations[platform].enabled
  )
}

// ─── Runtime helpers ────────────────────────────────────────────────────────
// Hand-written, NOT regenerated by apply-config. Provides the DB-backed
// `ClientConfig` shape used by the dashboard layout and setup wizard.

export type {
  ClientConfig,
  ProjectPlanning,
} from './client-config-runtime'

export {
  getClientConfig,
  getEnabledModules,
  getProjectPlanning,
  getScopeDocuments,
} from './client-config-runtime'
