'use server'

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { eq, isNull, and } from 'drizzle-orm'
import { db } from '@/lib/db/client'
import { scopeDocuments } from '@/lib/db/schema/scope-documents'
import { getSessionUser } from '@/lib/auth/session'

const MAX_BYTES = 25 * 1024 * 1024  // 25 MB per file
const ALLOWED_MIME = new Set([
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/plain',
  'text/markdown',
  'image/png',
  'image/jpeg',
  'image/webp',
])

/**
 * Browsers don't reliably tag .md files as `text/markdown` — Chrome/Edge
 * frequently send empty string or `text/plain`. Fall back to extension-based
 * inference so a markdown SOW upload doesn't get bounced as "unknown type".
 */
const EXT_TO_MIME: Record<string, string> = {
  '.md':       'text/markdown',
  '.markdown': 'text/markdown',
  '.txt':      'text/plain',
  '.pdf':      'application/pdf',
  '.doc':      'application/msword',
  '.docx':     'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls':      'application/vnd.ms-excel',
  '.xlsx':     'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt':      'application/vnd.ms-powerpoint',
  '.pptx':     'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.png':      'image/png',
  '.jpg':      'image/jpeg',
  '.jpeg':     'image/jpeg',
  '.webp':     'image/webp',
}

function resolveMimeType(filename: string, providedMime: string): string | null {
  if (providedMime && ALLOWED_MIME.has(providedMime)) return providedMime
  const ext = path.extname(filename).toLowerCase()
  const inferred = EXT_TO_MIME[ext]
  if (inferred && ALLOWED_MIME.has(inferred)) return inferred
  return null
}

export interface UploadResult {
  ok:       boolean
  document?: {
    id:         number
    filename:   string
    mimeType:   string
    sizeBytes:  number
    uploadedAt: string
  }
  error?:   string
}

/**
 * Persist a single uploaded scope document to disk + DB.
 *
 * Files are stored under `uploads/scope/<id>/<sanitized-filename>` keyed by
 * the autogenerated row id. The row is inserted first to claim the id, then
 * the file is written and `stored_path` is set. If the disk write fails the
 * row is hard-deleted so the table doesn't accumulate orphans.
 */
export async function uploadScopeDocument(formData: FormData): Promise<UploadResult> {
  const user = await getSessionUser()
  if (!user) return { ok: false, error: 'Sign in to upload.' }

  if (user.userType !== 'superadmin') {
    return { ok: false, error: 'Dashboard Setup is restricted to super admins.' }
  }

  const file = formData.get('file')
  if (!file || !(file instanceof File)) {
    return { ok: false, error: 'No file provided.' }
  }
  if (file.size === 0) return { ok: false, error: 'File is empty.' }
  if (file.size > MAX_BYTES) return { ok: false, error: 'File is larger than 25 MB.' }

  const resolvedMime = resolveMimeType(file.name, file.type)
  if (!resolvedMime) {
    return { ok: false, error: `Unsupported file type: ${file.type || 'unknown'}.` }
  }

  const safeName = sanitizeFilename(file.name)
  if (!safeName) return { ok: false, error: 'Invalid filename.' }

  // Insert row first so we have an id to scope the path on disk.
  const [inserted] = await db
    .insert(scopeDocuments)
    .values({
      filename:   safeName,
      storedPath: '', // filled in after we know the id
      mimeType:   resolvedMime,
      sizeBytes:  file.size,
      uploadedBy: user.id,
    })
    .returning({ id: scopeDocuments.id })
  if (!inserted) return { ok: false, error: 'Could not create document record.' }

  const dir         = path.join(process.cwd(), 'uploads', 'scope', String(inserted.id))
  const absPath     = path.join(dir, safeName)
  const relPath     = path.posix.join('uploads', 'scope', String(inserted.id), safeName)

  try {
    await mkdir(dir, { recursive: true })
    const bytes = Buffer.from(await file.arrayBuffer())
    await writeFile(absPath, bytes)
  } catch (err) {
    await db.delete(scopeDocuments).where(eq(scopeDocuments.id, inserted.id))
    console.error('[uploadScopeDocument] disk write failed:', err)
    return { ok: false, error: 'Failed to save file.' }
  }

  const [row] = await db
    .update(scopeDocuments)
    .set({ storedPath: relPath })
    .where(eq(scopeDocuments.id, inserted.id))
    .returning({
      id:         scopeDocuments.id,
      filename:   scopeDocuments.filename,
      mimeType:   scopeDocuments.mimeType,
      sizeBytes:  scopeDocuments.sizeBytes,
      uploadedAt: scopeDocuments.uploadedAt,
    })

  return { ok: true, document: row! }
}

/** Soft-delete a scope document. The file on disk is left in place — orphans are pruned later. */
export async function deleteScopeDocument(id: number): Promise<{ ok: boolean; error?: string }> {
  const user = await getSessionUser()
  if (!user) return { ok: false, error: 'Sign in to remove uploads.' }

  if (user.userType !== 'superadmin') {
    return { ok: false, error: 'Dashboard Setup is restricted to super admins.' }
  }

  if (!Number.isInteger(id) || id <= 0) return { ok: false, error: 'Invalid id.' }

  const now = new Date().toISOString()
  await db
    .update(scopeDocuments)
    .set({ deletedAt: now })
    .where(and(eq(scopeDocuments.id, id), isNull(scopeDocuments.deletedAt)))

  return { ok: true }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Strip path traversal + dangerous chars; keep ASCII alnum, dots, hyphens, underscores. */
function sanitizeFilename(name: string): string {
  const base = path.basename(name).trim()
  const cleaned = base
    .replace(/[^A-Za-z0-9._-]+/g, '_')
    .replace(/^\.+/, '')   // no leading dots
    .slice(0, 200)
  return cleaned || ''
}
